on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v1
    - uses: Azure/Synapse-workspace-deployment@V1.7.0
      with:
        TargetWorkspaceName: ${{ secrets.KGL_DEVOPS_PROD_SYNAPSENAME }}
        TemplateFile: ./synw-poc-esu2-01/TemplateForWorkspace.json
        ParametersFile: ./synw-poc-esu2-01/TemplateParametersForWorkspace.json
        environment: 'Azure Public'
        resourceGroup: ${{ secrets.KGL_DEVOPS_PROD_RGNAME }}
        clientId: ${{ secrets.KGL_DEVOPS_PROD_CLIENTID }}
        clientSecret: ${{ secrets.KGL_DEVOPS_PROD_SECRETKEY }}
        subscriptionId: ${{ secrets.KGL_DEVOPS_PROD_SUBCRIPTIONID }}
        tenantId: ${{ secrets.KGL_DEVOPS_PROD_TENANTID }}
        operation: 'deploy'
